name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        #Busqueda en el historial de commits
        fetch-depth: 0 
    # Versionamiento xemantico automatico
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version    
        # Autenticar en docker hub
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del step docker login"
        
    # Construcción de imagen
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build -t aldahirmayorga/docker-graphql:NEW_VERSION .
        docker build -t aldahirmayorga/docker-graphql:latest .

    # Push de imagen
    - name: Push Docker Image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        echo "Pushing Version $NEW_VERSION"
        docker push aldahirmayorga/docker-graphql:$NEW_VERSION
        docker push aldahirmayorga/docker-graphql:latest
